### Create contact
POST http://localhost:3000/contacts
Content-Type: application/json

{
    "name": "Elisa",
    "number": "+5521985015981",
    "email": "elisadrmnd@gmail.com",
    "dateOfBirth": "2001-07-23",
}

### Get all contacts
GET http://localhost:8000/contacts

### Get contact by ID
GET http://localhost:8000/contacts/1

### Get contact by name
GET http://localhost:8000/contacts/name

### Update contact
PATCH http://localhost:8000/contacts/1

### Delete contact
DELETE http://localhost:8000/contacts/1